cmd_drivers/gpu/arm/midgard/mali_kbase_smc.o := gcc -Wp,-MD,drivers/gpu/arm/midgard/.mali_kbase_smc.o.d  -nostdinc -isystem /usr/lib/gcc/arm-linux-gnueabihf/5/include -I/root/odroidxu3-3.10.y/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/root/odroidxu3-3.10.y/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/root/odroidxu3-3.10.y/include/uapi -Iinclude/generated/uapi -include /root/odroidxu3-3.10.y/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-exynos/include -Iarch/arm/plat-samsung/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -std=gnu89 -O2 -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_INSTRUMENTATION_LEVEL=0 -DMALI_RELEASE_NAME=\""r9p0-05rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_THIRDPARTY_PATH=../../drivers/gpu/arm/midgard/platform/"5422" -I/root/odroidxu3-3.10.y/drivers/staging/android -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform_dummy -I -Idrivers/gpu/arm/midgard/../../../base -I/root/odroidxu3-3.10.y/include/linux -Idrivers/gpu/arm/midgard/backend/gpu -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_INSTRUMENTATION_LEVEL=0 -DMALI_RELEASE_NAME=\""r9p0-05rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_THIRDPARTY_PATH=../../drivers/gpu/arm/midgard/platform/"5422" -I/root/odroidxu3-3.10.y/drivers/staging/android -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform_dummy -Idrivers/gpu/arm/midgard/../../../base -I/root/odroidxu3-3.10.y/include/linux -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform/5422 -Idrivers/gpu/arm/midgard/platform/5422 -Idrivers/gpu/arm/midgard/backend/gpu     -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(mali_kbase_smc)"  -D"KBUILD_MODNAME=KBUILD_STR(mali_kbase)" -c -o drivers/gpu/arm/midgard/mali_kbase_smc.o drivers/gpu/arm/midgard/mali_kbase_smc.c

source_drivers/gpu/arm/midgard/mali_kbase_smc.o := drivers/gpu/arm/midgard/mali_kbase_smc.c

deps_drivers/gpu/arm/midgard/mali_kbase_smc.o := \
    $(wildcard include/config/arm64.h) \

drivers/gpu/arm/midgard/mali_kbase_smc.o: $(deps_drivers/gpu/arm/midgard/mali_kbase_smc.o)

$(deps_drivers/gpu/arm/midgard/mali_kbase_smc.o):
